version: '3.7'
services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app
  #   environment:
  #     - NODE_ENV=development
  #     - PORT=3000
  #   depends_on:
  #     - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: mni
      POSTGRES_PASSWORD: mni
      POSTGRES_DB: mni
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data: