name: Release database export

on:
  schedule:
    # Run every day at midnight (00:00 UTC)
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  actions: write # Permission to delete old workflow runs
  contents: write # Permission to create releases

jobs:
  release_all_clusters:
    runs-on: ubuntu-latest
    steps:

      # For GH CLI
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set NOW
        id: set_now
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "data-${{ env.NOW }}"
          release_name: "Data export ${{ env.NOW }}"
          body: "Automated export of all cluster seed data."
          draft: false
          prerelease: false

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Download and upload cluster data sequentially
        env:
          API_KEY: ${{ secrets.DATABASE_EXPORT_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          UPLOAD_URL="${{ steps.create_release.outputs.upload_url }}"

          CLUSTERS=(
            SNDST-A CER-A CERS-A OCAN-A S-FRZ LUSH-A FRST-A VOLCA BAD-A HTFST-A OASIS-A
            V-SNDST-C V-CER-C V-CERS-C V-OCAN-C V-SWMP-C V-SFRZ-C V-LUSH-C V-FRST-C
            V-VOLCA-C V-BAD-C V-HTFST-C V-OASIS-C SNDST-C CER-C FRST-C SWMP-C
            M-SWMP-C M-BAD-C M-FRZ-C M-FLIP-C M-RAD-C M-CERS-C
          )

          for CLUSTER in "${CLUSTERS[@]}"; do
            echo "Processing $CLUSTER..."
            FILE_NAME="${CLUSTER}-data-${NOW}.zip"

            curl --fail -H "API_KEY: $API_KEY" \
              -o "$FILE_NAME" \
              "https://ingest.mapsnotincluded.org/export/$CLUSTER"

            echo "Uploading $FILE_NAME..."
            gh release upload "data-${NOW}" "$FILE_NAME" --clobber
          done

      - name: Delete old releases
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 1
          delete_tag_pattern: data-*
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
